//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Club</summary>
	[PublishedContentModel("Club")]
	public partial class Club : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Club";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Club(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Club, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Club address: The club's address
		///</summary>
		[ImplementPropertyType("clubAddress")]
		public string ClubAddress
		{
			get { return this.GetPropertyValue<string>("clubAddress"); }
		}

		///<summary>
		/// Club image: A picture that represents the club
		///</summary>
		[ImplementPropertyType("clubImage")]
		public IPublishedContent ClubImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("clubImage"); }
		}

		///<summary>
		/// Club logo: The clubs logo
		///</summary>
		[ImplementPropertyType("clubLogo")]
		public IPublishedContent ClubLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("clubLogo"); }
		}

		///<summary>
		/// Club name: The name of the sports club
		///</summary>
		[ImplementPropertyType("clubName")]
		public string ClubName
		{
			get { return this.GetPropertyValue<string>("clubName"); }
		}
	}
}
