//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Sponsor</summary>
	[PublishedContentModel("sponsor")]
	public partial class Sponsor : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sponsor";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Sponsor(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Sponsor, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Sponsor address: The sponsors address, can be a shop where a price can be picked up by the winner
		///</summary>
		[ImplementPropertyType("sponsorAddress")]
		public string SponsorAddress
		{
			get { return this.GetPropertyValue<string>("sponsorAddress"); }
		}

		///<summary>
		/// Sponsor logo: The sponsors logo
		///</summary>
		[ImplementPropertyType("sponsorLogo")]
		public IPublishedContent SponsorLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo"); }
		}

		///<summary>
		/// Sponsor name: The name of the sponsor
		///</summary>
		[ImplementPropertyType("sponsorName")]
		public string SponsorName
		{
			get { return this.GetPropertyValue<string>("sponsorName"); }
		}
	}
}
